"use client";
/**
 * Icon shim — re-exports Phosphor icons under the names the codebase
 * historically imported from `lucide-react`. Letting us swap the icon
 * family in one place without touching every callsite.
 *
 * `"use client"` is mandatory in Next 16: phosphor evaluates `createContext`
 * at module load. Without the directive, importing this file from a Server
 * Component fails during page-data collection ("createContext is not a
 * function"). With the directive, Server Components can still render
 * `<DollarSign />` etc — React 19 supports SC → CC rendering — and the
 * icon module lands in the client bundle as it always has.
 */
export {
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowLineDown as ArrowDownToLine,
  ArrowsDownUp as ArrowUpDown,
  ArrowLineUp as ArrowUpFromLine,
  At as AtSign,
  ChartBar as BarChart3,
  Barcode,
  Bell,
  Camera,
  CameraSlash,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Clock,
  CloudArrowUp as CloudUpload,
  CloudSlash as CloudOff,
  Copy,
  CurrencyDollar as DollarSign,
  Download,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  ClockCounterClockwise as History,
  IdentificationCard,
  Info,
  Key as KeyRound,
  Globe,
  GridFour as LayoutDashboard,
  SquaresFour as LayoutGrid,
  ListChecks,
  CircleNotch as Loader2,
  SignOut as LogOut,
  MapPin,
  Megaphone,
  List as Menu,
  ChatCircle as MessageCircle,
  Minus,
  Package,
  Package as PackageX,
  ArrowLineLeft as PanelRightClose,
  ArrowLineRight as PanelRightOpen,
  Pencil,
  Percent,
  Phone,
  Plus,
  PlusCircle,
  PlusSquare,
  Printer,
  Receipt,
  ArrowCounterClockwise as RotateCcw,
  Rows as Rows3,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  ShareNetwork as Share2,
  ShieldCheck,
  Basket as ShoppingBasket,
  ShoppingCart,
  Skull,
  Star,
  Storefront as Store,
  Tag,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Trophy,
  Truck,
  ArrowUUpLeft as Undo2,
  Upload,
  User,
  User as UserRound,
  Users,
  UsersThree as UsersGroup,
  Wallet,
  Wrench,
  X,
  XCircle,
  Lightning as Zap,
} from "@phosphor-icons/react";

export type { Icon as LucideIcon } from "@phosphor-icons/react";
