/**
 * Icon shim — re-exports Phosphor icons under the names the codebase
 * historically imported from `lucide-react`. Letting us swap the icon
 * family in one place without touching every callsite.
 *
 * Phosphor accepts `className`, `size`, `color`, and `weight`. Tailwind
 * size classes (e.g. `w-4 h-4`) work on the underlying <svg/>.
 */
export {
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowLineDown as ArrowDownToLine,
  ArrowsDownUp as ArrowUpDown,
  ArrowLineUp as ArrowUpFromLine,
  At as AtSign,
  ChartBar as BarChart3,
  Bell,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Clock,
  Copy,
  CurrencyDollar as DollarSign,
  Download,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  ClockCounterClockwise as History,
  Info,
  Key as KeyRound,
  GridFour as LayoutDashboard,
  SquaresFour as LayoutGrid,
  CircleNotch as Loader2,
  SignOut as LogOut,
  MapPin,
  Megaphone,
  List as Menu,
  ChatCircle as MessageCircle,
  Minus,
  Package,
  Package as PackageX,
  ArrowLineLeft as PanelRightClose,
  ArrowLineRight as PanelRightOpen,
  Pencil,
  Percent,
  Phone,
  Plus,
  PlusCircle,
  PlusSquare,
  Printer,
  Receipt,
  ArrowCounterClockwise as RotateCcw,
  Rows as Rows3,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  ShareNetwork as Share2,
  ShieldCheck,
  Basket as ShoppingBasket,
  ShoppingCart,
  Skull,
  Star,
  Storefront as Store,
  Tag,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Trophy,
  Truck,
  ArrowUUpLeft as Undo2,
  Upload,
  User,
  User as UserRound,
  Users,
  Wallet,
  Wrench,
  X,
  XCircle,
  Lightning as Zap,
} from "@phosphor-icons/react";

export type { Icon as LucideIcon } from "@phosphor-icons/react";
