import { NextResponse } from "next/server";
import { sql } from "drizzle-orm";
import { requireTenant } from "@/lib/api/auth-helpers";
import { withTenant } from "@/lib/db";
import { logActivity } from "@/lib/repo/activity";
import { rateLimit } from "@/lib/ratelimit";

// H11 — PDPL right-of-access export. Owner-only. Synchronous: streams a
// single JSON document containing every tenant-scoped table the user owns.
// All reads go through `withTenant`, so RLS catches any mistake. Rate-limited
// 2 / 24 h / user — a hostile script can't use this to dump-then-spam.
//
// **Synchronous on purpose for v1**: most tenants have <50 MB of data and
// finish well inside Next's default 300 s timeout. For larger tenants a
// background-queue + signed-link + email path is the right next step; tracked
// as a §4 follow-up.

const EXPORT_LIMIT = 2;
const EXPORT_WINDOW_SEC = 24 * 60 * 60;

// Tables to dump. Keep the list flat + alphabetised so a future schema
// addition is hard to forget — the tenant-deletion cron (H12) uses the same
// shape, so divergence is the signal.
const TABLES = [
  "activity_logs",
  "attendance_events",
  "attendance_settings",
  "branches",
  "brands",
  "categories",
  "category_attributes",
  "category_attribute_values",
  "customer_wallets",
  "customer_wallet_events",
  "employee_compensation",
  "expenses",
  "leave_requests",
  "notifications",
  "payment_attempts",
  "payroll_periods",
  "product_attribute_values",
  "product_history",
  "products",
  "purchase_order_items",
  "purchase_order_payments",
  "purchase_orders",
  "returns",
  "sales",
  "shop_settings",
  "store_locations",
  "subscriptions",
  "suppliers",
  "tasks",
  "tenant_members",
  "tenants",
] as const;

export async function POST() {
  const r = await requireTenant();
  if (!r.ok) return r.response;
  if (r.ctx.role !== "owner") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const rl = await rateLimit("account.export", r.ctx.userId, {
    limit: EXPORT_LIMIT,
    windowSec: EXPORT_WINDOW_SEC,
  });
  if (!rl.ok) {
    return NextResponse.json(
      { error: "محاولات كثيرة. حاول لاحقاً." },
      { status: 429 },
    );
  }

  const exported: Record<string, unknown[]> = {};
  await withTenant(r.ctx.tenantId, async (tx) => {
    for (const t of TABLES) {
      try {
        // Quoted identifier so a reserved word never trips us up; RLS
        // restricts visibility to the current tenant. Tables that don't
        // have `tenant_id` (e.g. attendance_settings could conceivably be
        // global one day) are still safe — RLS is the gate.
        const rows = await tx.execute(sql.raw(`SELECT * FROM "${t}"`));
        // drizzle's execute returns either a Result-like object with `.rows`
        // (postgres-js driver) or a plain array depending on the call shape.
        exported[t] = Array.isArray(rows)
          ? (rows as unknown[])
          : ((rows as { rows?: unknown[] }).rows ?? []);
      } catch (err) {
        exported[t] = [
          {
            __error: err instanceof Error ? err.message : String(err),
          },
        ];
      }
    }
  });

  const manifest = {
    exportedAt: new Date().toISOString(),
    tenantId: r.ctx.tenantId,
    schemaVersion: 27, // matches the latest migration journal idx
    tables: TABLES,
    note:
      "Generated by /api/account/export. Each top-level key is the database " +
      "table name; the value is the array of rows the requesting user can see " +
      "under PostgreSQL RLS scoped to their tenant.",
  };

  const body = JSON.stringify({ manifest, data: exported }, null, 2);

  logActivity({
    tenantId: r.ctx.tenantId,
    actorUserId: r.ctx.userId,
    action: "auth.data_export",
    category: "auth",
    entityType: "user",
    entityId: r.ctx.userId,
    metadata: { byteSize: body.length, tables: TABLES.length },
  });

  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Content-Disposition": `attachment; filename="matgary-export-${r.ctx.tenantId.slice(0, 8)}-${new Date().toISOString().slice(0, 10)}.json"`,
      "Cache-Control": "no-store",
    },
  });
}
